### ISSUE TITLE
Skip instead of fail if helm directory is absent

### ISSUE THREAD

**Issue by gintautassulskus** [microbean/helm-maven-plugin#29]
Hi,

Not every submodule in a multi-module maven project has/requires helm charts. 
I suggest adding a parameter to skip projects that do not have `src/main/helm` folder automatically. 
The existing `<skip>` option forces me to replicate plugin's configuration across multiple submodules in order to explicitly specify which submodule should be skipped or not.

**Comment by ljnelson** [comment]
Hi; thanks for your input and for using the `helm-maven-plugin`!  I appreciate the time you took to file this issue.

There isn't anywhere in the codebase that requires a `src/main/helm` directory, either as a hard coded value or a default.

I'll play around with a multimodule situation, however, and see if I can get at the "spirit" of this issue; maybe there is an option or two I could add to make them easier.

**Comment by ljnelson** [comment]
I think what you may be getting at can be found here: https://github.com/microbean/helm-maven-plugin/blob/v2.7.0.1.0.33/src/main/java/org/microbean/helm/maven/InstallReleaseMojo.java#L183-L192

I do in spirit like the idea of a `lenient` parameter or something similar to simply skip execution if required bits are missing (with a warning of course).

**Comment by gintautassulskus** [comment]
Hi @ljnelson,
And thank you for this contribution!

Sorry for the unrefined submission. I will try to address this now.

My use case for helm maven plugin is a typical multi-module maven project. The root `pom.xml` defines common dependencies versions which are then inherited by modules. The modules can always override the settings if need be. The idea is to reduce code repetition and increase consistency across modules.

Having said the above, it would be great if I could define defaults for `helm:*` goals and run them either against all modules `mvn helm:*` or just against a specific one `-pl module`. Since not every module may require/have helm charts, it would be convenient to have an option to skip such modules. At the moment the workaround is to reintroduce plugin configuration in modules without helm charts and add the <skip> tag:
```
                <configuration>
                    <version>1</version> <-- mandatory
                    <releaseName>${project.artifactId}</releaseName> <-- mandatory
                    <skip>true</skip>
                </configuration>
```
However, besides the `skip` tag I have to re-specify mandatory `version` and `releaseName` values as well. Note that contrary to [the usage guide](https://microbean.github.io/helm-maven-plugin/usage.html), I am not associating the confguration with a maven phase - I am using the `confguration` tag outside the `execution` tag.

As an alternative to the above, the `lenient` parameter with the behaviour as you described could do the trick. In my opinion, this should apply to all relevant operations, e.g. package, install. An example of a similar behaviour is [asciidoctor](https://github.com/asciidoctor/asciidoctor-maven-plugin) maven plugin for `asciidoc` processing. If the directory does not exist, it simply emits the following line and continues:
`[INFO] sourceDirectory /Users/.../src/docs/asciidoc does not exist. Skip processing`

PS. The `src/main/helm` path was specified by me.
I have just checked Helm conventions and realised that my decision to change the default chart path was wrong. The default path, specified in the plugin code, looks like the best approach. Although specifying chart folder name as `${project.artifactId}` feels redundant (if we consider a single-chart folder).
